name: rostok
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0
  auto_route: ^9.3.0
  get_it: ^8.0.3
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  dio: ^5.7.0
  sms_autofill: ^2.4.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.2.0
  talker_flutter: ^5.0.0
  talker_dio_logger: ^5.0.0
  talker_riverpod_logger: ^5.0.0
  intl: ^0.20.2
  shimmer: ^3.0.0
  share_plus: ^12.0.1
  video_player: ^2.10.1
  google_fonts: ^6.3.2
  font_awesome_flutter: ^10.9.0
  url_launcher: ^6.3.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  extra_pedantic: ^4.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.4
  auto_route_generator: ^9.3.1


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-VariableFont_opsz,wght.ttf

    - family: NyghtSerif
      fonts:
        - asset: assets/fonts/nyght/NyghtSerif-Light.ttf
          weight: 300
        - asset: assets/fonts/nyght/NyghtSerif-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/nyght/NyghtSerif-Regular.ttf
          weight: 400
        - asset: assets/fonts/nyght/NyghtSerif-RegularItalic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/nyght/NyghtSerif-Medium.ttf
          weight: 500
        - asset: assets/fonts/nyght/NyghtSerif-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/nyght/NyghtSerif-Bold.ttf
          weight: 700
        - asset: assets/fonts/nyght/NyghtSerif-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/nyght/NyghtSerif-Dark.ttf
          weight: 900
        - asset: assets/fonts/nyght/NyghtSerif-DarkItalic.ttf
          weight: 900
          style: italic


